import { Inter } from 'next/font/google'
import './globals.css'
import CustomHead from './head'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Student Control',
  description: 'Generated by Y1 & M8',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <CustomHead/>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
